<?php
/** Approved Home presentation; Client marquee and service index use separate CMS collections. */
defined( 'ABSPATH' ) || exit;
$page = get_queried_object_id();
$line_1 = showmakers_page_copy( $page, 'home_hero_line_1' );
$line_2 = showmakers_page_copy( $page, 'home_hero_line_2' );
$introduction = showmakers_page_copy( $page, 'home_hero_introduction' );
$support = showmakers_page_copy( $page, 'home_hero_supporting_copy' );
$cta = showmakers_page_copy( $page, 'home_hero_cta_label' );
?>
<section class="hero" aria-labelledby="hero-title"><div class="shell hero-inner"><div class="hero-intro"><h1 id="hero-title"><?php if ( $line_1 !== '' ) : ?><span><?php echo esc_html( $line_1 ); ?></span><?php endif; if ( $line_2 !== '' ) : ?><span><?php echo esc_html( $line_2 ); ?></span><?php endif; if ( $line_1 === '' && $line_2 === '' ) echo esc_html( get_the_title( $page ) ); ?></h1></div><?php if ( $introduction !== '' || $support !== '' || $cta !== '' ) : ?><div class="hero-support"><?php if ( $introduction !== '' || $support !== '' ) : ?><div class="hero-explanation"><?php if ( $introduction !== '' ) : ?><p class="hero-introduction"><?php echo esc_html( $introduction ); ?></p><?php endif; if ( $support !== '' ) : ?><p><?php echo esc_html( $support ); ?></p><?php endif; ?></div><?php endif; if ( $cta !== '' ) : ?><a class="arrow-link" href="<?php echo esc_url( home_url( '/work/' ) ); ?>" data-event="hero_view_work"><?php echo esc_html( $cta ); ?><svg class="ui-arrow" viewBox="0 0 64 16" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="square" stroke-linejoin="miter"><path d="M2 8H60M54 2L60 8L54 14"/></svg></a><?php endif; ?></div><?php endif; ?><div class="hero-collage" aria-hidden="true"><img src="<?php echo esc_url( showmakers_asset_url( 'images/hero/showmakers-hero-collage.webp' ) ); ?>" width="2048" height="768" alt="" decoding="async" fetchpriority="high"></div></div></section><?php get_template_part( 'template-parts/clients-marquee' ); ?><section class="shell home-services" aria-labelledby="home-services-title"><div class="home-services-heading"><h2 id="home-services-title">What we do</h2><a class="arrow-link home-services-route" href="<?php echo esc_url( home_url( '/services/' ) ); ?>">All Services<svg class="ui-arrow" viewBox="0 0 64 16" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="square" stroke-linejoin="miter"><path d="M2 8H60M54 2L60 8L54 14"/></svg></a></div><ol class="home-service-index"><?php foreach ( showmakers_visible_services() as $service ) : ?><li><a href="<?php echo esc_url( home_url( '/services/' ) . '#' . $service->slug ); ?>"><span class="home-service-number"><?php echo esc_html( sprintf( '%02d', (int) get_term_meta( $service->term_id, 'sort_order', true ) ) ); ?></span><span><?php echo esc_html( $service->name ); ?></span></a></li><?php endforeach; ?></ol></section>
